<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

     <ItemGroup>
         <PackageReference Include="Avalonia" />
         <PackageReference Include="Avalonia.Controls.DataGrid" />
         <PackageReference Include="Avalonia.Desktop" />
         <PackageReference Include="Avalonia.Themes.Fluent" />
         <PackageReference Include="Avalonia.Fonts.Inter" />
         <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
         <PackageReference Include="Avalonia.Diagnostics" >
             <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
             <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
         </PackageReference>
         <PackageReference Include="CommunityToolkit.Mvvm" />
         <PackageReference Include="FluentAvaloniaUI" />
         <PackageReference Include="Microsoft.AspNetCore" />
         <PackageReference Include="Newtonsoft.Json" />
         <PackageReference Include="Portable.BouncyCastle"/> 
         <PackageReference Include="System.Security.Cryptography.Pkcs" />
         <PackageReference Include="System.Security.Cryptography.Xml"/>
     </ItemGroup>

     <ItemGroup>
         <ProjectReference Include="..\AvaloniaXplat.Shared\AvaloniaXplat.Shared.csproj" />
         <ProjectReference Include="..\AvaloniaXplat.DesktopServices\AvaloniaXplat.DesktopServices.csproj" />
     </ItemGroup>
</Project>
